module.exports={
    uri:"basic",
    name:"Basic Profile",
    icon:"basic-profile.png",
    questions:[
        {
            name:"fn",
            label:[{lang:"en",value:"First Name"},{lang:"fr",value:"Prénom"}],
            type:"text",
            class:"col-sm-6",
            points:1,
            required:true,
            editable:false
        },
        {
            name:"ln",
            label:[{lang:"en",value:"Last Name"},{lang:"fr",value:"Nom"}],
            type:"text",
            class:"col-sm-6",
            points:1,
            required:true,
            editable:false
        },
        {
            name:"email",
            label:[{lang:"en",value:"Email"},{lang:"fr",value:"Email"}],
            type:"email",
            class:"col-sm-6",
            points:1,
            required:true,
            editable:false
        },
        {
            name:"workemail",
            label:[{lang:"en",value:"Work Email"},{lang:"fr",value:"Email professionnel"}],
            type:"email",
            class:"col-sm-6",
            points:1,
            required:false,
            editable:true
        },
        {
            name:"phone",
            label:[{lang:"en",value:"Phone"},{lang:"fr",value:"Téléphone"}],
            type:"tel",
            class:"col-sm-6",
            points:1,
            required:true,
            editable:false
        },
        {
            name:"phone1",
            label:[{lang:"en",value:"Alternate Number"},{lang:"fr",value:"Téléphone alternatif"}],
            type:"tel",
            class:"col-sm-6",
            points:1,
            required:false,
            editable:true
        },
        {
            name:"dob",
            label:[{lang:"en",value:"Date of Birth"},{lang:"fr",value:"Date de naissance"}],
            type:"date",
            class:"col-sm-6",
            points:1,
            required:true,
            editable:false
        },
        {
            name:"age",
            label:[{lang:"en",value:"Age"},{lang:"fr",value:"Age"}],
            type:"text",
            class:"col-sm-6",
            points:1,
            required:false,
            editable:false,
            option:{
                endpoint:"/api/v1/age",
                method:"POST",
                params:["dob"]
            }
        },
        {
            name:"country",
            label:[{lang:"en",value:"Country"},{lang:"fr",value:"Pays"}],
            type:"select",
            class:"col-sm-6",
            points:1,
            required:true,
            editable:false,
            option:{
                endpoint:"/api/v1/country",
                method:"GET",
                params:[]
            }
        },
        {
            name:"city",
            label:[{lang:"en",value:"City"},{lang:"fr",value:"Ville"}],
            type:"select",
            class:"col-sm-6",
            points:1,
            required:true,
            editable:false,
            option:{
                endpoint:"/api/v1/city",
                method:"POST",
                params:["country"]
            }
        },
        {
            name:"zipcode",
            label:[{lang:"en",value:"Zip Code"},{lang:"fr",value:"Code postal"}],
            type:"select",
            class:"col-sm-6",
            points:1,
            required:true,
            editable:false,
            option:{
                endpoint:"/api/v1/zipcode",
                method:"POST",
                params:["country","city"]
            }
        },
        {
            name:"ethinicity",
            label:[{lang:"en",value:"Please Select your ethinicity"},{lang:"fr",value:"Sélectionnez votre ethnicité"}],
            type:"select",
            class:"col-sm-6",
            points:1,
            required:true,
            editable:false,
            option:{
                endpoint:"/api/v1/ethinicity",
                method:"GET",
                params:[]
            }
        },
        {
            name:"origin",
            label:[{lang:"en",value:"Are you of Hispanic, Latino, or Spanish origin?"},{lang:"fr",value:"Êtes-vous de l'origine hispanique, latino ou espagnole?"}],
            type:"select",
            class:"col-sm-6",
            points:1,
            required:true,
            editable:false,
            option:{
                endpoint:"/api/v1/origin",
                method:"GET",
                params:[]
            }
        },
        {
            name:"education",
            label:[{lang:"en",value:"What is the highest level of education you have completed?"},{lang:"fr",value:"Quel est le plus haut niveau d'éducation que vous avez terminé?"}],
            type:"select",
            class:"col-sm-6",
            points:1,
            required:true,
            editable:true,
            option:{
                endpoint:"/api/v1/education",
                method:"GET",
                params:[]
            }
        },
        {
            name:"relationship",
            label:[{lang:"en",value:"What is your relationship status?"},{lang:"fr",value:"Quel est votre statut de relation?"}],
            type:"select",
            class:"col-sm-6",
            points:1,
            required:true,
            editable:true,
            option:{
                endpoint:"/api/v1/relationship",
                method:"GET",
                params:[]
            }
        },
        {
            name:"children",
            label:[{lang:"en",value:"How many children do you have?"},{lang:"fr",value:"Combien de enfants avez-vous?"}],
            type:"select",
            class:"col-sm-6",
            points:1,
            required:true,
            editable:true,
            option:{
                endpoint:"/api/v1/children",
                method:"GET",
                params:["relationship"]
            }
        },
        {
            name:"interests",
            label:[{lang:"en",value:"Please choose your hobbies and interests"},{lang:"fr",value:"Sélectionnez vos loisirs et intérêts"}],
            type:"checkbox",
            class:"col-sm-12",
            points:5,
            required:true,
            editable:true,
            option:{
                endpoint:"/api/v1/interests",
                method:"GET",
                params:[]
            }
        },
        {
            name:"surveycategory",
            label:[{lang:"en",value:"Please choose the categories you would be interested to get the participation in future surveys"},{lang:"fr",value:"Sélectionnez les catégories que vous seriez intéressé à participer aux sondages futures"}],
            type:"checkbox",
            class:"col-sm-12",
            points:5,
            required:true,
            editable:true,
            option:{
                endpoint:"/api/v1/surveycategory",
                method:"GET",
                params:[]
            }
        }
    ]
}